package com.example.recipeplanner

import androidx.annotation.DrawableRes

// Object for single recipe with basic information
data class Recipes(
    val name: String,
    val prepTimeMin: Int,
    val cookTimeMin: Int,
    val ingredients: List<String>,
    val directions: List<String>,
    val servings: Int,
    val meal: String,
    @DrawableRes val image: Int? = null
)

 // sample recipe list
val recipe = mutableListOf(
    Recipes("Chicken Pillows", 20, 30,
        listOf("1lb Chicken Breast, diced", "1 Tbsp Cooking Oil", "2 Tbsp Minced Garlic",
            "2 Tbsp Italian Seasoning","8oz Onion and Chive Cream Cheese",
            "2 cans Crescent Rolls", "12oz Chicken Gravy, canned or homemade",
            "1/2 cup Italian Breadcrumbs"),
        listOf("Pre-heat oven to 375F. In large skillet on medium-high heat add cooking oil and garlic till fragrant",
            "Add chicken to skillet, cook through, add seasonings and salt & pepper to taste",
            "Add cream cheese to chicken, mix thoroughly.",
            "Fill crescent rolls with chicken mix, then roll in breadcrumbs before placing on baking sheet.",
            "Cook pillows according to crescent roll packaging, while cooking add gravy to skillet with leftover " +
                    "chicken & cream cheese mixture. Serve warm over mashed potatoes or rice."),
        6, "Dinner", R.drawable.chickenpillows),
    Recipes("Creamy Cavatappi", 10, 20,
        listOf("8 ounces (1/2 pound) cavatappi pasta",
            "1 tablespoon unsalted butter",
            "2 cloves garlic, minced",
            "3/4 cup heavy cream",
            "1/2 teaspoon kosher salt, plus more for the pasta water",
            "1/2 teaspoon finely ground black pepper",
            "1/2 cup (1.3 ounces) finely grated Parmesan cheese, plus more for garnish",
            "1 tablespoon fresh lemon juice",
            "1 cup frozen peas, optional",
            "1/4 cup to 1/2 cup reserved pasta cooking water"),
        listOf("Put a large pot of water on to boil over high heat. Season generously with salt, add the pasta and stir. Cook until just short of al dente, according to the package directions.",
            "While the pasta cooks, add the butter to a large skillet over medium heat, add garlic and cook just until fragrant.",
            "Slowly add the cream while stirring and season with salt and pepper. Bring to a simmer, reducing the heat if needed to maintain a simmer. Cook, while stirring, until slightly thickened, about 3 minutes.",
            "Add the Parmesan a small handful at a time, sprinkling it over top and stirring each time until melted. Add the lemon juice and stir. Turn the heat as low as it’ll go until the pasta is ready, stirring occasionally.",
            "Add the pasta and peas to the sauce. Add 1/4 cup of the reserved pasta water and turn the heat to medium. Toss constantly until you have a creamy sauce that coats the noodles, 3 to 5 minutes. If the sauce seems too thick, add more pasta water a small splash at a time, tossing in between.",
            "Taste, adding salt and/or pepper if needed. Top with a sprinkle of Parmesan cheese and serve immediately."),
        3, "Dinner", R.drawable.creamycavatappi),
    Recipes("Sausage And Gnocchi Skillet", 10, 20,
        listOf("2 Tbsp Cooking Oil",
            "1 (12-ounce) package chicken sausage links, sliced",
            "1 (16-ounce) package shelf-stable gnocchi",
            "1 (15-ounce) jar sun-dried tomato sauce",
            "½ cup water",
            "5 ounces baby spinach leaves",
            "¼ cup chopped fresh basil leaves, plus more for garnish",
            "½ cup shaved or shredded Parmesan cheese"),
        listOf("Add oil to a large skillet over medium-high heat.",
            "Add the sliced chicken sausage and cook until a little browned, 3-4 minutes, stirring occasionally.",
            "Add the gnocchi and sun-dried tomato sauce to the skillet. Add the water to the sauce jar and give it a shake before adding the water to the skillet. Stir to combine.",
            "Bring the mixture just to a simmer, then reduce the heat to medium. Cook until the gnocchi are soft, 3-5 minutes.",
            "Add the spinach and basil to the skillet and stir to combine. Reduce heat to low then cover the skillet and cook until the spinach is wilted, 2-3 minutes.",
            "Sprinkle with Parmesan cheese and additional basil before serving."),
        4, "Dinner", R.drawable.sausagegnocchiskillet),
    Recipes("Easy Stove Top Pork Chops", 10, 40,
        listOf("3 Thick Cut Pork Chops",
            "1 tsp Garlic Powder",
            "1 tsp Onion Powder",
            "2 tsp Brown Sugar",
            "2 tsp Dried Thyme",
            "1.5 tsp Dried Oregano",
            "2 tsp Salt",
            "1 tsp Pepper",
            "1 (12 oz.) Jar Pork Gravy"),
        listOf("Combine seasonings in a small bowl and fully coat the pork chops with the mix.",
            "Heat oil in a skillet on medium-high and sear the pork chops until brown on all sides, about 5 mins.",
            "Cover the pork chops with gravy and turn heat to low, scraping up the brown bits from the bottom of the skillet.",
            "Let simmer for about 30 mins, until done, 145F inside temperature. Serve warm over mashed potatoes or rice."),
        4, "Dinner", R.drawable.stovetopporkchop),
    Recipes("Fudgey Browines", 10, 25,
        listOf("1/2 cup unsalted butter (melted and HOT)",
            "1 & 1/8 cup granulated sugar",
            "1 Tbsp vegetable or avocado oil",
            "2 large eggs",
            "1 Tbsp vanilla extract",
            "1 tsp salt",
            "1/2 cup flour",
            "1/2 cup cocoa powder",
            "1/2 cup chocolate chips or chopped nuts"),
        listOf("Pre-heat oven to 350F. Coat 8\"x8\" or 9\"x9\" dish in cooking spray.",
            "Combine hot butter, sugar and oil, whisk well until combined.",
            "Beat eggs separately and add to mix, add vanilla, beat for about a minute",
            "Sift in flour and cocoa powder (add chocolate chips or nuts if using) do NOT overmix!",
            "Bake for 23-26 minutes."),
        9, "Dessert", R.drawable.fugeybrownies),

    Recipes("Cinnamon Roll French Toast Bake", 15, 45,
        listOf("1/4 cup melted butter",
            "2 cans cinnamon rolls",
            "4 eggs",
            "1/2 cup half & half (or regular milk)",
            "2 tsp cinnamon",
            "2 tsp vanilla extract",
            "1 cup maple syrup"),
        listOf("Pre-heat oven to 375F. Pour melted butter into 13\"x9\" baking dish.",
            "Set icing aside for later, cut rolls into 8 even pieces and add to dish.",
            "Beat eggs, then beat in cream, cinnamon and vanilla until well mixed. Pour over cinnamon rolls, and drizzle with syrup.",
            "Bake for 20-30 minutes (until golden).",
            "Once cooled, drizzle with icing."),
        12, "Breakfast", R.drawable.cinnrollfrenchtoast),
    Recipes("Chocolate Chip Cookies", 15,20,
        listOf("1 cup softened butter (not melted)",
            "1 cup granulate sugar",
            "1 cup light brown sugar",
            "2 tsp vanilla extract",
            "2 eggs",
            "2 cups flour",
            "1 tsp baking soda",
            "1/2 tsp baking powder",
            "1 tsp salt",
            "2 tsp cinnamon",
            "2 cup chocolate chips"),
        listOf("Pre-heat over to 350F, line baking sheet with parchment paper.",
            "Cream together butter and sugar.",
            "Beat in eggs and vanilla until fluffy.",
            "In separate bowl, mix flour, baking soda, baking powder, salt and cinnamon; then mix into wet ingredients.",
            "Add chocolate chips to mix.",
            "Roll 2-3 Tbsp of dough at a time to form cookies. Bakes for 12 minutes, until just barely browning.",
            "Let sit on sheet for 2 minutes then move to cooling rack."),
        30, "Dessert", R.drawable.chocchipcookies),
     Recipes("Overnight Oats", 10,10,
         listOf("1/2 cup whole rolled oats",
             "1 tablespoon chia seeds",
             "1/2 teaspoon maple syrup",
             "Pinch sea salt",
             "1/4 cup greek yogurt",
             "2/3 cups unsweet almond milk"
         ),
         listOf("Place the oats, chia seeds, maple syrup, salt,yogurt in a lidded jar",
             "Pour in the almond milk, and stir thouroughly to combine.",
             "Cover and store overnight in the fridge"),
         1, "Breakfast", R.drawable.oats),

     Recipes("Avocado Toast", 5,5,
         listOf("2 slices of toasted bread",
             "1 large avocado",
             "1 teaspoon fresh lemon juice",
             "2 teaspoon extra virgin olive oil",
             "Pinch of seasalt",
             "Pinch of black pepper"
         ),
         listOf("In a small bowl gently mash peeled and pitted avocado with lemon juice.",
             "Divide and spread the mashed avocado across the two slices of bread.",
             "brizzle each slice of avocado toast with extra virgin oive oil and sprinke with seasalt and pepper."),
         2, "Breakfast", R.drawable.avocado),

     Recipes("Quiche", 15,35,
         listOf("1 single pie crust unbaked",
             "6 large eggs",
             "3/4 cups of milk",
             "3/4 teaspoon salt",
             "1/4 teaspoon black pepper",
             "1 1/2 cups shredded cheddar cheese",
             "1 cup cubed cooked ham",
             "2 tablespoons sliced green onions",
         ),
         listOf("Preheat oven to 375 F. Unroll pie crust and press into 9 inch pie plate.",
             "In a large bowl, whisk eggs, milk, salt, and pepper",
             "sprinkle ham, 1 cup of cheese and green onion into pie crust and pour egg mixture on top",
             "Sprinkle remaining 1/2 cup of cheese on top of egg mixture.",
             "Bake for 35-40 minutes. Let cool for 5-10 minutes."),
         6, "Breakfast", R.drawable.quiche),

     Recipes("Sausage Breakfast Hash", 15,50,
         listOf("1.6 lb potatoes",
             "1 1/2 tbsp olive oil",
             "1/2 tsp paprika",
             "1/2 tsp thyme",
             "1/4 tsp onion powder",
             "1/2 tsp garlic powder",
             "1/2 tsp salt",
             "1 bell pepper",
             "1 red onion",
             "1 tbsp olive oil",
             "4 oz bacon",
             "1 lb sausage",
             "5 large eggs",
         ),
         listOf("Preheat Oven to 400 F. Toss potatoes with oil and seasonings in a bowl.",
             "Spread mixture on large tray. Bake for 15 minutes.",
             "Squeeze dollops on sausage on top of potatoes, scatter bacon as well",
             "Bake for 20 minutes. Toss, then bake for another 15 minutes.",
             "Crack eggs on top and return into oven for 7 minutes"),
         4, "Breakfast", R.drawable.hash),


    Recipes("Fluffy Pancakes", 5,10,
        listOf("1 1/2 cups all purpose flour",
            "2 1/2 teaspoons baking powder",
            "1/2 teaspoon salt",
            "1 tablespoon sugar",
            "1 1/4 sups milk",
            "1 egg",
            "3 tablespoons butter, melted",
            "2 teaspoons vanilla extract (optional)",
            ),
     listOf("In a large bowl, sift together the flour, baking powder, salt and sugar.",
         "Make a well in the middle and pour in the milk, egg, butter and vanilla extract.",
         "Combine until mostly smooth.",
         "Heat a large pan over medium-high heat. Once hot, grease, spray or melt butter on the pan.",
         "Pour 1/4 cup of pancake batter onto pan.",
         "Cook pancakes for about 2 minutes, until edges begin to look defined and bubbles form.",
         "Flip the pancakes over and cook for another minute on the other side",
         "Remove pancakes from pan onto a plate and keep warm while cooking the rest of the batter."),
        4, "Breakfast", R.drawable.pancake),
     Recipes("Egg Bites", 10,40,
         listOf("2 tablespoons olive oil",
             "1/2 red onion, diced",
             "1/2 chopped red pepper",
             "1 cup chopped broccoli florets",
             "1 small zucchini, diced",
             "2 cloves of garlic, minced",
             "1 1/2 packed cups baby spinach",
             "10 large eggs",
             "3/4 cup cottage cheese",
             "1 teaspoon salt",
             "1/2 teaspoon black pepper",
             "1 teaspoon dried oregano",
             "2/3 cup grated cheddar cheese",
             "8 ounces bacon, cooked and crumbled (optional)"),
         listOf("Pre-heat over to 350F, and grease a muffin pan with butter or cooking spray ",
             "Heat the olive oil over medium-high heat in a large skillet.",
             "Add the onion and bell pepper and saute for 2 minutes. Then add brocoli and zucchini.",
             "Saute until vegtables has softened. Add garlic and spinach and saute for a minute",
             "Turn off heat and set pan aside.",
             "Add the ggs, cottage cheese, salt, pepper and oregano into a blender and blend until well combined.",
             "Add sauteed veggies, egg micture, cheese and bacon into large mixing bowl and stir",
             "Ladle egg micture into muffin pan filling each to the top",
             "Bake for 22-25 minutes",
             "Remove pan from oven and let egg bites cool for 5 minutes before removing."),
         12, "Breakfast", R.drawable.eggbites),

     Recipes("Garlic Butter Steak Bites", 5,10,
         listOf("1 tbsp olive oil",
             "1 1/2 lb sirloin steak",
             "1/2 tsp salt",
             "1/2 tsp pepper",
             "2 tbsp butter",
             "4 minced garlic cloves",
             "1 tablespoon parsley"),
         listOf("Add olive oil into large skillet and heat over high heat.",
             "Add steak peices and season them generously with salt and papper.",
             "Transfer steak bites into a plate and in the same skillet as butter and garlic.",
             "Cook util garlic starts to brown. Pour garlic butter over steak bites and toss well.",
             "Garnish with parsley and serve"),
         4, "Dinner", R.drawable.steak),

     Recipes("Chicken Quesadilla", 10,20,
         listOf("1 tbsp oil",
             "1 lb chicken breast cut into small peices.",
             "1 tbso taco seasoning",
             "1/2 large bell pepper diced",
             "1/2 yellow onion diced",
             "2 tbsp unsalted butter",
             "6 flour tortillas",
             "2 cups mexican cheese"),
         listOf("Preheat a skillet with oil on medium high. Add in chicek and taco seasoning.Cook for 4 minutes",
             "Add in bell pepper and onion, cook for another 5 minutes or until chicken and veggies are cooked",
             "On a clean skillet, add butter and place tortilla on top.",
             "Add mexican cheese and chicken mixture on half of torilla.",
             "Top with more cheese, fold over tortilla to close",
             "Cook one side until tortilla is golden brown."),
         6, "Dinner", R.drawable.quesadilla),

     Recipes("Italian Meatballs", 30,120,
         listOf("1/4 cup olive oil",
             "1/2 cup mined yellow onions",
             "2 tsp minced garlic",
             "6 ounces tomato paste",
             "7 cup crushed canned tomatoes",
             "2 tsp kosher salt",
             "2 lb ground beef",
             "2 large eggs",
             "1 cup plain breadcrumbs",
             "1/2 cup grated parmesan cheese",
             "1/2 cup finely minced yellow onion",
             "1 tsp minced garlic",
             "1/4  cup sliced basil")
         ,
         listOf("In a large pot, heat oil over medium heat. Add onion, garlic and saute for 4 minutes",
             "Stir in tomato paste and cook for 1 minutes. Stir in crushed tomatoes, salt, and pepper.",
             "Simmer covered for 30 minutes. Add seasoning to taste.",
             "Heat over to broil. Line a large baking sheet with foil and lighlty grease with olive oil.",
             "In a lagre bowl mix ground beef, eggs, breadcrumbs, parmeasan cheese, onion, and garlic.",
             "Measure out 1/3 cup of beef mixture and evening space on baking sheet.",
             "Cook until surface is browned for 10 minutes, flip meatballs and cook for addional 3 minutes.",
             "Transfer meatballs into tomato sauce. Simmer on low for 20 minutes."),
         14, "Dinner", R.drawable.meatball),

     Recipes("Cake Pops", 60,120,
         listOf("1 box vanilla cake mix",
             "1/4 cup vegatable oil",
             "1/2 cup unsalted butter",
             "1 cup powdered sugar",
             "1 tsp vanilla extract",
             "1 tsp milk",
             "3 1/2 cups candy melts.",
             "40 cake pop sticks",
             "1 pack sprinkles"),
         listOf("Make boxed cake mix as directed on box. Before mixing all ingredients, add in the vegatable oil.",
             "Allow cake to cool for 15 minutes. Break the cake apart with hands and crumble up completely.",
             "In a medium sized bowl add butter, icing sugar, vanill and milk",
             "Mix for 4 minutes until light and fluffy",
             "Add 3/4 of frosting into the crumbled cake and mix until combined",
             "Roll tbsps full of cake mixture into round balls and place on lined tray",
             "Place tray in freezer for 40 minutes",
             "Melt candy melts. Dip cake pop stick into melted chocolate and then into cake ball.",
             "Grab cake ball by stick and place into melted choclate. Decorate with sprinkles."),
         40, "Dessert", R.drawable.cakepop),

     Recipes("Vanilla Cake", 20, 30,
         listOf("2 cups all purpose flour",
             "2 1/2 teaspoons baking powder",
             "1/4 tsp Kosher salt",
             "4 large eggs",
             "1 1/2 cups granulated sugar",
             "1 cup milk",
             "6 tsp vanilla extract",
             "2 tsp vegetable oil",
             "2 1/2 sticks unsalted butter",
             "1 lb powdered sugar",
             "2-4 tbsp full fat milk"),
         listOf("Preheat oven to 350 F. Grease 2, 8 inch cake pans with butter.",
             "Whisk flour, baking powder and salt in a large bowl and set aside.",
             "Beat eggs for 30 seconds while pouring over sugar, then beat for 7 minutes until white",
             "Place butter and milk in microwave for 2 minutes, and gently add the flour until mixed in",
             "Pour hot milk, vanilla and oil into now empty flour bowl",
             "Add egg batter into milk batter and whisk until smooth.",
             "Pour batter into pans and bale for 30 minutes until golden",
             "Remove from oven and then cool for 20 minutes while making vanilla buttercream.",
             "Beat butter in stand mizer until fluffy, ass powdered sugar until fluffy",
             "Add vanilla and milk and beat for 30 seconds.",
             "Frost your bottom cake. Put other cake ontop and finish frosting entire cake.",
             "Optionally top with sprinkles"),
         12, "Dessert", R.drawable.cake),

     Recipes("Homemade Vanilla Ice Cream", 30, 120,
         listOf("1 1/2 cups heavy cream",
             "1 1/2 cups whole milk",
             "2/3 cups cane sugar",
             "2 teaspoons vanilla extract",
             "1/8 teaspoon sea salt"),
         listOf("In a medium saucepan, combine the cream, milk, sugar, vanilla and salt.",
             "Warm over medium-low heat, whisking often, for 5 minutes, or until sugar dissolves and mixture is warmed thorughout",
             "Pour into a bowl, cover, and chill for 2 hours or overnight",
             "Remove chilled ice cream base form fridge and whisk well",
             "Mix for 20-30 minutes which will make the ice cream soft.",
             "Transfer into an airtight container and freeze for 2 hours."),
         4, "Dessert", R.drawable.icecream),


     Recipes("Homemade Churros", 20, 10,
         listOf("2/3 cup all purpose flour",
             "1/4 stick unsalted butter",
             "1 cup water",
             "pinch of salt",
             "2 tsp sugar",
             "1 egg",
             "oil (for frying)"),
         listOf("Place water, butter, sugar and pinch of salt into saucepan, bring to a boil",
             "Add flour and mix until dough forms",
             "Remove from stove and let cool. Add egg and work into dough",
             "Pour oil into a large frying pan. Fill a piping bag with the dough.",
             "Pipe the dough directly into the hot oil. They will only need about 2 minutes or until golden.",
             "Place on paper towl to rid excess oil.",
             "Roll into sugar and ground cinnamon"),
         60, "Dessert", R.drawable.churro),

     Recipes("Lemon Bars", 22, 55,
         listOf("3 cups all purpose flour",
             "2/3 cups powdered sugar",
             "1/2 tsp salt",
             " 1/2 tbsp unsalted butter",
             "3 tbsp lemon zest",
             "8 large eggs",
             "1 cup lemon juice"),
         listOf("Heat oven to 350F. Whisk together flour, powdered sugar and salt.",
             "Pour in melted butter and mix until combined",
             "Sprinked the dough into lined pan and press down into a flat layer. Bake for 20 minutes",
             "Add suagr and zest for 3 lemons into food processor until light yellow color.",
             "Add suagr and remaining flour into large bowl and mix well.",
             "Pour in lemon juice and add eggs. Mix until completely combined.",
             "Pour filling onto warm crust then transfer to over and bake for 25 minutes.",
             "All to chill in fridge for two hours.",
             "Dust with powdered sugar and cut into bars."),
         4, "Dessert", R.drawable.lemon),




 )