package com.example.recipeplanner

import androidx.annotation.DrawableRes

// Object for single recipe with basic information
data class Recipes(
    val name: String,
    val prepTimeMin: Int,
    val cookTimeMin: Int,
    val ingredients: List<String>,
    val directions: List<String>,
    val servings: Int,
    val meal: String,
    @DrawableRes val image: Int? = null
)

 // sample recipe list
val recipe = mutableListOf(
    Recipes("Chicken Pillows", 20, 30,
        listOf("1lb Chicken Breast, diced", "1 Tbsp Cooking Oil", "2 Tbsp Minced Garlic",
            "2 Tbsp Italian Seasoning","8oz Onion and Chive Cream Cheese",
            "2 cans Crescent Rolls", "12oz Chicken Gravy, canned or homemade",
            "1/2 cup Italian Breadcrumbs"),
        listOf("Pre-heat oven to 375F. In large skillet on medium-high heat add cooking oil and garlic till fragrant",
            "Add chicken to skillet, cook through, add seasonings and salt & pepper to taste",
            "Add cream cheese to chicken, mix thoroughly.",
            "Fill crescent rolls with chicken mix, then roll in breadcrumbs before placing on baking sheet.",
            "Cook pillows according to crescent roll packaging, while cooking add gravy to skillet with leftover " +
                    "chicken & cream cheese mixture. Serve warm over mashed potatoes or rice."),
        6, "Dinner", R.drawable.chickenpillows),
    Recipes("Creamy Cavatappi", 10, 20,
        listOf("8 ounces (1/2 pound) cavatappi pasta",
            "1 tablespoon unsalted butter",
            "2 cloves garlic, minced",
            "3/4 cup heavy cream",
            "1/2 teaspoon kosher salt, plus more for the pasta water",
            "1/2 teaspoon finely ground black pepper",
            "1/2 cup (1.3 ounces) finely grated Parmesan cheese, plus more for garnish",
            "1 tablespoon fresh lemon juice",
            "1 cup frozen peas, optional",
            "1/4 cup to 1/2 cup reserved pasta cooking water"),
        listOf("Put a large pot of water on to boil over high heat. Season generously with salt, add the pasta and stir. Cook until just short of al dente, according to the package directions.",
            "While the pasta cooks, add the butter to a large skillet over medium heat, add garlic and cook just until fragrant.",
            "Slowly add the cream while stirring and season with salt and pepper. Bring to a simmer, reducing the heat if needed to maintain a simmer. Cook, while stirring, until slightly thickened, about 3 minutes.",
            "Add the Parmesan a small handful at a time, sprinkling it over top and stirring each time until melted. Add the lemon juice and stir. Turn the heat as low as it’ll go until the pasta is ready, stirring occasionally.",
            "Add the pasta and peas to the sauce. Add 1/4 cup of the reserved pasta water and turn the heat to medium. Toss constantly until you have a creamy sauce that coats the noodles, 3 to 5 minutes. If the sauce seems too thick, add more pasta water a small splash at a time, tossing in between.",
            "Taste, adding salt and/or pepper if needed. Top with a sprinkle of Parmesan cheese and serve immediately."),
        3, "Dinner", R.drawable.creamycavatappi),
    Recipes("Sausage And Gnocchi Skillet", 10, 20,
        listOf("2 Tbsp Cooking Oil",
            "1 (12-ounce) package chicken sausage links, sliced",
            "1 (16-ounce) package shelf-stable gnocchi",
            "1 (15-ounce) jar sun-dried tomato sauce",
            "½ cup water",
            "5 ounces baby spinach leaves",
            "¼ cup chopped fresh basil leaves, plus more for garnish",
            "½ cup shaved or shredded Parmesan cheese"),
        listOf("Add oil to a large skillet over medium-high heat.",
            "Add the sliced chicken sausage and cook until a little browned, 3-4 minutes, stirring occasionally.",
            "Add the gnocchi and sun-dried tomato sauce to the skillet. Add the water to the sauce jar and give it a shake before adding the water to the skillet. Stir to combine.",
            "Bring the mixture just to a simmer, then reduce the heat to medium. Cook until the gnocchi are soft, 3-5 minutes.",
            "Add the spinach and basil to the skillet and stir to combine. Reduce heat to low then cover the skillet and cook until the spinach is wilted, 2-3 minutes.",
            "Sprinkle with Parmesan cheese and additional basil before serving."),
        4, "Dinner", R.drawable.sausagegnocchiskillet),
    Recipes("Easy Stove Top Pork Chops", 10, 40,
        listOf("3 Thick Cut Pork Chops",
            "1 tsp Garlic Powder",
            "1 tsp Onion Powder",
            "2 tsp Brown Sugar",
            "2 tsp Dried Thyme",
            "1.5 tsp Dried Oregano",
            "2 tsp Salt",
            "1 tsp Pepper",
            "1 (12 oz.) Jar Pork Gravy"),
        listOf("Combine seasonings in a small bowl and fully coat the pork chops with the mix.",
            "Heat oil in a skillet on medium-high and sear the pork chops until brown on all sides, about 5 mins.",
            "Cover the pork chops with gravy and turn heat to low, scraping up the brown bits from the bottom of the skillet.",
            "Let simmer for about 30 mins, until done, 145F inside temperature. Serve warm over mashed potatoes or rice."),
        4, "Dinner", R.drawable.stovetopporkchop),
    Recipes("Fudgey Browines", 10, 25,
        listOf("1/2 cup unsalted butter (melted and HOT)",
            "1 & 1/8 cup granulated sugar",
            "1 Tbsp vegetable or avocado oil",
            "2 large eggs",
            "1 Tbsp vanilla extract",
            "1 tsp salt",
            "1/2 cup flour",
            "1/2 cup cocoa powder",
            "1/2 cup chocolate chips or chopped nuts"),
        listOf("Pre-heat oven to 350F. Coat 8\"x8\" or 9\"x9\" dish in cooking spray.",
            "Combine hot butter, sugar and oil, whisk well until combined.",
            "Beat eggs separately and add to mix, add vanilla, beat for about a minute",
            "Sift in flour and cocoa powder (add chocolate chips or nuts if using) do NOT overmix!",
            "Bake for 23-26 minutes."),
        9, "Dessert", R.drawable.fugeybrownies),

    Recipes("Cinnamon Roll French Toast Bake", 15, 45,
        listOf("1/4 cup melted butter",
            "2 cans cinnamon rolls",
            "4 eggs",
            "1/2 cup half & half (or regular milk)",
            "2 tsp cinnamon",
            "2 tsp vanilla extract",
            "1 cup maple syrup"),
        listOf("Pre-heat oven to 375F. Pour melted butter into 13\"x9\" baking dish.",
            "Set icing aside for later, cut rolls into 8 even pieces and add to dish.",
            "Beat eggs, then beat in cream, cinnamon and vanilla until well mixed. Pour over cinnamon rolls, and drizzle with syrup.",
            "Bake for 20-30 minutes (until golden).",
            "Once cooled, drizzle with icing."),
        12, "Breakfast", R.drawable.cinnrollfrenchtoast),
    Recipes("Chocolate Chip Cookies", 15,20,
        listOf("1 cup softened butter (not melted)",
            "1 cup granulate sugar",
            "1 cup light brown sugar",
            "2 tsp vanilla extract",
            "2 eggs",
            "2 cups flour",
            "1 tsp baking soda",
            "1/2 tsp baking powder",
            "1 tsp salt",
            "2 tsp cinnamon",
            "2 cup chocolate chips"),
        listOf("Pre-heat over to 350F, line baking sheet with parchment paper.",
            "Cream together butter and sugar.",
            "Beat in eggs and vanilla until fluffy.",
            "In separate bowl, mix flour, baking soda, baking powder, salt and cinnamon; then mix into wet ingredients.",
            "Add chocolate chips to mix.",
            "Roll 2-3 Tbsp of dough at a time to form cookies. Bakes for 12 minutes, until just barely browning.",
            "Let sit on sheet for 2 minutes then move to cooling rack."),
        30, "Dessert", R.drawable.chocchipcookies),

    Recipes("Fluffy Pancakes", 5,10,
        listOf("1 1/2 cups all purpose flour",
            "2 1/2 teaspoons baking powder",
            "1/2 teaspoon salt",
            "1 tablespoon sugar",
            "1 1/4 sups milk",
            "1 egg",
            "3 tablespoons butter, melted",
            "2 teaspoons vanilla extract (optional)",
            ),
     listOf("In a large bowl, sift together the flour, baking powder, salt and sugar.",
         "Make a well in the middle and pour in the milk, egg, butter and vanilla extract.",
         "Combine until mostly smooth.",
         "Heat a large pan over medium-high heat. Once hot, grease, spray or melt butter on the pan.",
         "Pour 1/4 cup of pancake batter onto pan.",
         "Cook pancakes for about 2 minutes, until edges begin to look defined and bubbles form.",
         "Flip the pancakes over and cook for another minute on the other side",
         "Remove pancakes from pan onto a plate and keep warm while cooking the rest of the batter."),
        4, "Breakfast", R.drawable.pancake),
     Recipes("Egg Bites", 10,40,
         listOf("2 tablespoons olive oil",
             "1/2 red onion, diced",
             "1/2 chopped red pepper",
             "1 cup chopped broccoli florets",
             "1 small zucchini, diced",
             "2 cloves of garlic, minced",
             "1 1/2 packed cups baby spinach",
             "10 large eggs",
             "3/4 cup cottage cheese",
             "1 teaspoon salt",
             "1/2 teaspoon black pepper",
             "1 teaspoon dried oregano",
             "2/3 cup grated cheddar cheese",
             "8 ounces bacon, cooked and crumbled (optional)"),
         listOf("Pre-heat over to 350F, and grease a muffin pan with butter or cooking spray ",
             "Heat the olive oil over medium-high heat in a large skillet.",
             "Add the onion and bell pepper and saute for 2 minutes. Then add brocoli and zucchini.",
             "Saute until vegtables has softened. Add garlic and spinach and saute for a minute",
             "Turn off heat and set pan aside.",
             "Add the ggs, cottage cheese, salt, pepper and oregano into a blender and blend until well combined.",
             "Add sauteed veggies, egg micture, cheese and bacon into large mixing bowl and stir",
             "Ladle egg micture into muffin pan filling each to the top",
             "Bake for 22-25 minutes",
             "Remove pan from oven and let egg bites cool for 5 minutes before removing."),
         12, "Breakfast", R.drawable.eggbites)





 )